import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const inter = Poppins({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
  weight: ['300', "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <body
        className={`${inter.className} antialiased text-default/95 scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
